[workspace]
members = ["impl"]

[package]
name = "textwrap-macros"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"

[dependencies.proc-macro-hack]
version = "0.5"

[dependencies.textwrap-macros-impl]
version = "0.1.0"
path = "./impl"
